openapi: 3.0.0
info:
  title: Exploratory Demo API
  version: v1
  description: Simple API to demo the API Builder in Postman
  contact:
    name: Pavan Kumar
    email: ppkumar@merkleinc.com
servers:
  - url: http://localhost:3000
    description: Demo API
paths:
  /videos:
    get:
      operationId: allVideos
      summary: returns an array of videos 
      description: Returns a list of all the Exploratory videos
      tags:
        - videos
      responses:
        '200':
          description: List of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/video"

  /videos/{videoId}:
    get:
      operationId: One Video
      summary: returns a single video 
      description: Returns a video for given Id
      tags:
        - videos
      parameters:
          - name: videoId
            in: path
            required: true
            schema:
                type: number
                example: 1
      responses:
        '200':
          description: Single video
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/video"

components:
  schemas:
    video:
      type: object
      properties:
        name:
          type: string
          description: Video title
          example: "Public Workspaces"
        url:
          type: string
          description: Video URL
          example: "https://www.youtube.com/watch?v=DjGbMdqnY64"
        views:
          type: number
          description: Number of views
          example: 7483

tags:
  - name: videos
    description: API returning info about Exploratory videos
